name: 🚀 Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2 and restart service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Help-Hinderer-Online-Multiplayer-Game || git clone https://github.com/${{ github.repository }}.git Help-Hinderer-Online-Multiplayer-Game
            cd Help-Hinderer-Online-Multiplayer-Game
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskgame
